pipeline:

  amd64:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/kresus-amd64
    tag: latest
    dockerfile: Dockerfile-nightly.amd64

  arm32v7:
    image: plugins/docker
    registry: no-cloud.fr
    repo: no-cloud.fr/kresus-arm
    tag: latest
    dockerfile: Dockerfile-nightly.arm

  multiarch:
    image: docker:dind
    environment:
      - DOCKER_CLI_EXPERIMENTAL=enabled
    commands:
      - docker manifest create no-cloud.fr/kresus-multiarch no-cloud.fr/kresus-arm no-cloud.fr/kresus-amd64
      - docker manifest annotate no-cloud.fr/kresus-multiarch no-cloud.fr/kresus-amd64 --arch amd64
      - docker manifest annotate no-cloud.fr/kresus-multiarch no-cloud.fr/kresus-arm --arch arm
      - docker manifest push no-cloud.fr/kresus-multiarch

  notify:
    image: no-cloud.fr/drone-xmpp
    secrets: [ xmpp_host, xmpp_jid, xmpp_password, xmpp_to ]
    when:
      status: [ success, failure ]
